### PR TITLE
feat(Deploy) Implement skip path option (#54)

### PR DESCRIPTION
**Pull request by johanhammar**
Implements a skip path option, -S/--skip-path to skip files and directories that match the given path. The skip path option can be repeated.

### CODE REVIEW

**Comment by johanhammar** [comment]
A first shot at implementing a skip path option. Could be useful but needs more thoroughly testing

**Comment by johanhammar** [comment]
Needs to be tested a bit more. I will open the PR again when I have tested it more

**Comment by johanhammar** [comment]
More testing done. Please let me know if the PR is ok or if I should change anything

**Comment by Mierenga** [comment]
Hi @johanhammar, thanks for the PR for this feature!

To merge this in, we also need the skipping behavior to apply to the `wipe` command. This means it should apply to the [`wipe(args)` step in `deploy.ts`](https://github.com/Kong/kong-portal-cli/blob/master/src/commands/deploy.ts#L111), as well as when running `portal wipe <workspace>` from the command line.

Without applying also to `wipe`, it would delete any skipped files rather than preserve them. When running `deploy` with skipped paths, we want to leave skipped files as they are rather than delete them.

Also, would you be able to use eslint to enforce this repo's code style? There were a few style issues in the filter loop that should be easy to adjust. If you use VS Code, you can install this extension to see the warnings: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Finally, prior to merging your branch in, it will need to be rebased with `master`.

**Comment by johanhammar** [comment]
Thanks for the feedback!

I'll try to squeeze in some time after the  vacation and implement according to your comments👍

**Comment by johanhammar** [comment]
Hi @Mierenga 

Apparently my rebase did not go as intended. I'll open a new PR

**Comment by Mierenga** [comment]
Hi @johanhammar, a merge is also ok if that will simplify it since we will squash when putting onto master.

**Comment by johanhammar** [comment]
Thanks! Maybe I was a bit too fast closing this PR. Anyway #63 should be a bit cleaner atleast

**Pull request closed without merging**
