### PR TITLE
feat(*): refactor portal CLI 

### PR DESCRIPTION
**Pull request by HenriPro**
Refactor to clean up code. Removes server and config commands.

### CODE REVIEW

**Review by Jlawlzz — CHANGES_REQUESTED** [review]
looks like axios is not a dependency

**Review by Jlawlzz — COMMENTED** [review]
When I run `portal enable default` it also runs the `config` command

**Comment by HenriPro** [comment]
> looks like axios is not a dependency

Good catch, I think I removed it pruning deps. I wanted to use a tool to do it, but I couldn't find one easily :/

**Comment by HenriPro** [comment]
> When I run `portal enable default` it also runs the `config` command

I can see why you would think that, but it only displays the cli config. This happens on every command.   displays previously this ran on `deploy` and `fetch`.

This is different from the `config` command which displays all config information

**Comment by HenriPro** [comment]
> > When I run `portal enable default` it also runs the `config` command
> 
> I can see why you would think that, but it only displays the cli config. This happens on every command. Previously this ran on `deploy` and `fetch`.
> 
> This is different from the `config` command which displays all config information

On further thought, there is no need for this to show. Removed mini config on every commmand.

**Comment by HenriPro** [comment]
> > When I run `portal enable default` it also runs the `config` command
> 
> I can see why you would think that, but it only displays the cli config. This happens on every command. Previously this ran on `deploy` and `fetch`.
> 
> This is different from the `config` command which displays all config information

On further thought, there is no need for this to show. Removed mini config on every commmand.

**Review by Jlawlzz — APPROVED** [review]
LGTM 🚀

**Pull request merged**
